notifications:
  email: false
language: python
sudo: required
matrix:
  include:
#  The linux build is performed on appveyor because during development it was easier to use than travis.
#  We will keep the linux entry here, and the corresponding linux-specific code below, in case there is a need
#  to switch from appveyor to travis for linux builds.
#  - os: linux
#    services: docker
#    env: DOCKER_LIBLSL=alpine DOCKER_PYLSL=henriquegemignani/docker-nod-ci
  - os: osx
    language: generic
    env: PIP=pip2 CIBW_PLATFORM=macos
env:
  global:
  - TWINE_USERNAME=cboulay
# Note: TWINE_PASSWORD is set in Travis settings
  - CIBW_TEST_COMMAND='python -c "import pylsl; print(pylsl.library_version()); print(pylsl.local_clock())"'
  - CIBW_BUILD_VERBOSITY=3

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker pull $DOCKER_LIBLSL; fi

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker run --rm -v $(pwd):/host -w /host $DOCKER_LIBLSL ./ci/build_liblsl_linux.sh;fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  git clone https://github.com/sccn/liblsl.git;
  cd liblsl;
  mkdir build && cd build;
  cmake -DCMAKE_INSTALL_PREFIX=../../pylsl/ -DLSL_UNIXFOLDERS=ON ..;
  cmake --build . --config Release --target install;
  cd ../..;
  fi

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker pull $DOCKER_PYLSL;
  fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker run --rm -v $(pwd):/host -w /host $DOCKER_PYLSL ./ci/build_wheels_linux.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    $PIP install cibuildwheel;
    cibuildwheel --output-dir dist;
  fi

#after_failure:

before_deploy:
- python -m pip install --upgrade twine

# deploy working dir is /home/travis/build/labstreaminglayer/liblsl-Python
deploy:
  skip_cleanup: true
  provider: script
  script:
  - python -m twine upload dist/*.whl
  on:
    tags: true
