version: 1.14.1.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: "Ubuntu1804"
  URL_PREFIX: https://github.com/sccn/liblsl/releases/download/v1.14.1b5/liblsl-1.14.1-
  TWINE_USERNAME: cboulay
# Note: TWINE_PASSWORD is set in Appveyor web settings

#https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#running-windows-and-linux-builds-side-by-side
build_script:
- python -m pip install --user --upgrade setuptools wheel
- ps: >-
        $files = @{
                win_amd64 = 'Win_amd64.zip'
                win32 = 'Win_i386.zip'
                manylinux1_x86_64 = 'manylinux1_x64.so'
                macosx_10_13_x86_64 = 'OSX_amd64.tar.bz2'
                };

        ls;

        $files.GetEnumerator() | foreach -Process {
                iwr ($env:URL_PREFIX + $_.value) -ErrorAction Stop -OutFile $_.value;

                iex "mkdir -p pylsl/lib";

                if($_.value.EndsWith('.7z')) {
                        iex "7z e $($_.value) bin/liblsl* -Opylsl/lib"
                }
                if($_.value.Endswith('.zip')) {
                        iex "unzip -oj $($_.value) bin/lsl* -d pylsl/lib"
                }
                if($_.value.EndsWith('.so')) {
                        Copy-Item $_.value -Destination pylsl/lib/liblsl.so
                }
                if($_.value.Endswith('.bz2')) {
                        # https://xkcd.com/1168/
                        tar xvf $_.value --wildcards -C pylsl 'lib/liblsl*'
                }

                ls pylsl/lib/
                python setup.py bdist_wheel -p $_.key
                Remove-Item -Path pylsl/lib/* -Force -Recurse
                Remove-Item -Path build -Force -Recurse

                #if($_.value.StartsWith('manylinux2010')) {
                #    python -m pip install --user dist/pylsl-1.14.0-py2.py3-none-manylinux2010_x86_64.whl
                #    python -c 'import pylsl; print(pylsl.library_info()); pylsl.stream_outlet(pylsl.stream_info());'
                #}

        };

        if ($env:APPVEYOR_REPO_TAG -eq "true") {
                python -m pip install --user twine
                python -m twine upload dist/*.whl
        } else {
                echo "Not uploading to pypi; APPVEYOR_REPO_TAG : $env:APPVEYOR_REPO_TAG"
        }
artifacts:
- path: "dist/*.whl"
  name: Wheels

